[package]
name = "with-state"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.10"
shuttle-axum = { version = "0.16.0", path = "../../../services/shuttle-axum" }
shuttle-runtime = { version = "0.16.0", path = "../../../runtime" }
tokio = { version = "1.26.0" }
